# Generated by Django 5.0.3 on 2024-05-22 18:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("combine", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="collection",
            name="highlighted",
            field=models.BooleanField(default=False),
        ),
    ]
